### ISSUE TITLE
Jade is now Pug

### ISSUE THREAD

**Issue by jdevega** [redradix/redux-base-app#16]
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

**Comment by acontreras89** [comment]
Running `npm list jade` displays where this dependency comes from:

```
redux-base-app@0.1.0 /home/aaron/redradix/tenpercent/redux-base-app
└─┬ mocha@2.2.5
  └── jade@0.26.3
```

This was never fixed in mocha as they stopped depending on pug/jade when version 3 was released, as stated [in this comment](https://github.com/mochajs/mocha/issues/2200#issuecomment-235493858).

I have created #23 to (at some point) update mocha to version 3. However, I don't know if some sort of migration would be needed. I'm closing this issue in favor of that one.
