### ISSUE TITLE
Errors in current router

### ISSUE THREAD

**Issue by acontreras89** [redradix/redux-base-app#27]
I know it has been suggested to upgrade react router to the next version. In the meanwhile, however, I think we should address the problems affecting our current router.

In particular, the hack to [add dispatch to route handlers](https://github.com/redradix/redux-base-app/blob/master/src/index.js#L26-L39) is working poorly in some scenarios:

* When `<IndexRoute>` components are used, as their hooks are not being properly _hacked_
* When other components (e.g. `<Redirect>`) are used, which have their custom hooks. The problem here seems to be related to the arguments order

I can fix this (I did it for one of my projects), but I know @kanedaki has used a different approach in some projects. Could you explain the differences/benefits of the new strategy?

**Comment by kanedaki** [comment]
I think the main purpose of that mix is having dispatch available inside onEnter hook.

But you can get similar or even better results wrapping your router

'''
import React from 'react'
import { render } from 'react-dom'
import { Provider } from 'react-redux'
import { Router, browserHistory } from 'react-router'
import configureStore from 'core/store/configure-store'
import configureRoutes from 'core/routes'
import { syncHistoryWithStore } from 'react-router-redux'

const store = configureStore()
const history = syncHistoryWithStore(browserHistory, store)

render(
  <Provider store={store}>
    <Router history={history} routes={configureRoutes({dispatch: store.dispatch, getState: store.getState})} />
  </Provider>,
  document.getElementById('root')
)
'''

**Comment by cdelaorden** [comment]
That hack is not needed at all: you can either inject "dispatch" to the Router itself as a prop and it will be available as a prop on the Route params, or either connect(s=>{}) the router, that will inject no "state props" but will inject dispatch function to the Router itself again.

Third option, most elegant to me: instead of returning the routes directly from the ./routes file, wrap it in a function that receives the store, so that closure will make store.dispatch and store.getState available inside your routes.

So this line:
```
const routes = mixDispatch(createRoutes(rawRoutes))
```

Would become:
```

const routes = createRoutes(rawRoutes(store))
```

And the route definition returns a function instead of the route set.

**Comment by acontreras89** [comment]
Thanks @cdelaorden, that sounds pretty neat to me.
I can see this is what @kanedaki was trying to show as well.

I will fix this as soon as I have a couple of minutes to spare.

**Comment by acontreras89** [comment]
:ship: :tada:
